name: Rubocop

on: [push]

jobs:
  rubocop:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --local

      - run: bin/rubocop

